# @package _global_

data:
  datasets:
    type: SemanticKITTI
    splits: [train, val, test]
    data_root: /project/aimm/SSC/SemanticKITTI
    label_root: /project/aimm/SSC/SemanticKITTI/dataset/labels
    depth_root: /project/aimm/SSC/SemanticKITTI/dataset/depth
    frustum_size: 8
  loader:
    batch_size: 1
    num_workers: 2

model:
  channels: 64
  scene_size: [256, 256, 32]
  volume_scale: 2
  num_classes: 20

evaluator:
  type: SSCMetrics
  num_classes: 20
